language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: nightly
    - php: 7.0
      env: COVERAGE=yes
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true
before_install:
  - composer self-update
install:
  - sudo apt-get remove gearman-job-server
  - sudo apt-get install gearman-job-server libgearman-dev
  - printf "\n"| pecl install gearman-1.0.3
  - composer update $COMPOSER_FLAGS --no-interaction --prefer-source
script:
  - gearmand -d
  - ./bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - ./bin/test-reporter
notifications:
  email: false
