language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
before_install:
  - composer self-update
install:
  - sudo apt-get remove gearman-job-server
  - sudo apt-get install gearman-job-server libgearman-dev
  - printf "\n"| pecl install gearman-1.0.3
  - composer install
script:
  - gearmand -d
  - phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover
